# Generated by Django 4.2 on 2026-06-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_scadaalert_tasktemplate_workorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scadaalert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={},
        ),
    ]
